# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
  config.vm.box = "centos65_x64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.define :server do |sv|
    #sv.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
    sv.vm.network :private_network, ip: "192.168.33.10"
    sv.vm.hostname = "server"
  end
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "System01/site-cookbooks"
    chef.data_bags_path = ["System01/data_bags"]
    chef.environments_path = "System01/environments"
    chef.nodes_path = "System01/nodes"
    #chef.environment = ""
    #chef.recipe_url = ""
    #chef.roles_path = "System01/roles"
    chef.add_recipe "production"
    #chef.add_role ""

    # You may also specify custom JSON attributes:
    #chef.json = { :mysql_password => "foo" }
  end
end
