# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
  config.vm.box = "centos72_x64"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.synced_folder ".", "/vagrant"

  nodes = %w(manager1 worker1 worker2)
  ips = %w(192.168.33.100 192.168.33.120 192.168.33.121)
  (nodes.zip(ips)).each do |n, ip|
    config.vm.define n do |sv|
      sv.vm.network :private_network, ip: ip
      sv.vm.hostname = n
      sv.vm.provision "shell", inline: <<-SHELL
        curl -fsSL https://get.docker.com/ | sh
        usermod -aG docker vagrant
        systemctl start docker
        systemctl enable docker.service
        systemctl stop firewalld
        systemctl disable firewalld.service
      SHELL
    end
  end

  config.vm.define "client" do |sv|
    sv.vm.network :private_network, ip: "192.168.33.150"
    sv.vm.hostname = "client"
    sv.vm.provision "shell", inline: <<-SHELL
        curl -fsSL https://get.docker.com/ | sh
        usermod -aG docker vagrant
        systemctl start docker
        systemctl enable docker.service
        systemctl stop firewalld
        systemctl disable firewalld.service
      SHELL
  end

end
