- name: Install NTPd
  yum: name=ntp state=present
- name: Configure NTP
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart NTPd
- name: be sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
