# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.box = "centos65_x64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "256"
  end

  config.vm.define :server do |sv|
    node_ipaddress = "192.168.33.10"
    sv.vm.hostname = "mrtg.localdomain"
    sv.vm.network "private_network", ip: node_ipaddress
    sv.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
    sv.vm.provision "shell", inline: <<-SHELL
      ln -sf /usr/share/zoneinfo/right/Asia/Tokyo /etc/localtime
      yum install -y ntp ntpdate
      service ntpdate start
      chkconfig ntpdate on
      service ntpd start
      chkconfig ntpd on
      service vboxadd-service stop
      service vboxadd stop

      yum install -y httpd mrtg net-snmp net-snmp-utils
      sed -i -e 's/^#//' /etc/cron.d/mrtg
      service crond restart
    SHELL
  end
end
