# -*- mode: ruby -*-

ENV["ANSIBLE_NOCOWS"] = "1"

Vagrant.configure(2) do |config|
  config.vm.box = "centos65_x64"
  config.vm.define :node1 do |node|
    node.vm.hostname = "node1"
    node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :private_network, ip: "192.168.33.11"
  end
  config.vm.define :node2 do |node|
    node.vm.hostname = "node2"
    node.vm.network :forwarded_port, guest: 22, host: 2002, id: "ssh"
    node.vm.network :forwarded_port, guest: 80, host: 8000, id: "http"
    node.vm.network :private_network, ip: "192.168.33.12"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.host_key_checking = false
    #ansible.verbose = "vvvv"
    ansible.playbook = "playbooks/site.yml"
    ansible.groups = {
      "webservers" => ["node1"],
      "others" => ["node2"],
      "all_groups:children" => ["webservers", "others"]
    }
  end
end
