# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65_x64"

  config.vm.define :db1 do |sv|
    node_ipaddress = "192.168.33.10"
    sv.vm.hostname = "db1.localdomain"
    sv.vm.network :private_network, ip: node_ipaddress
    sv.vm.provision :shell, :path => "prov.sh", :privileged => true, :args => "'#{node_ipaddress}'"
  end
  config.vm.define :db2, autostart: false do |sv|
    node_ipaddress = "192.168.33.11"
    sv.vm.hostname = "db2.localdomain"
    sv.vm.network :private_network, ip: node_ipaddress
    sv.vm.provision :shell, :path => "prov.sh", :privileged => true, :args => "'#{node_ipaddress}'"
  end
  config.vm.define :db3, autostart: false do |sv|
    node_ipaddress = "192.168.33.12"
    sv.vm.hostname = "db3.localdomain"
    sv.vm.network :private_network, ip: node_ipaddress
    sv.vm.provision :shell, :path => "prov.sh", :privileged => true, :args => "'#{node_ipaddress}'"
  end
end
