# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65_x64"
  config.vm.provision :shell, :path => "prov.sh"

  config.vm.define :db1 do |sv|
    sv.vm.network :private_network, ip: "192.168.33.10"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end

  end
  config.vm.define :db2, autostart: false do |sv|
    sv.vm.network :private_network, ip: "192.168.33.11"
  end
end
