# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
  config.vm.box = "centos72_x64"

  config.vm.box_check_update = false
  config.ssh.insert_key = true
  config.vm.synced_folder ".", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL

  config.vm.define :gitlab do |sv|
    #sv.vm.network "forwarded_port", guest: 80, host: 8080
    sv.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
    #sv.vm.network "private_network", ip: "192.168.33.10"
    sv.vm.hostname = "gitlab.localdomain"
    sv.vm.provision "shell", inline: <<-SHELL
      ln -sf /usr/share/zoneinfo/right/Asia/Tokyo /etc/localtime
      yum install -y ntp ntpdate
      sed -i -e "/^server /d" /etc/ntp.conf
      echo "server ntp.jst.mfeed.ad.jp iburst prefer" >> /etc/ntp.conf
      echo "ntp.jst.mfeed.ad.jp" > /etc/ntp/step-tickers
      systemctl start ntpdate
      systemctl enable ntpdate
      systemctl start ntpd
      systemctl enable ntpd
      systemctl stop vboxadd-service
      systemctl stop vboxadd

      # sudo yum install -y curl policycoreutils openssh-server openssh-clients
      # sudo systemctl enable sshd
      # sudo systemctl start sshd
      # sudo yum install -y postfix
      # sudo systemctl enable postfix
      # sudo systemctl start postfix
      # sudo systemctl start postfix
      sudo yum install -y httpd
      sudo systemctl enable httpd
      #sudo systemctl start httpd
      sudo firewall-cmd --permanent --add-service=http
      sudo systemctl reload firewalld

      sudo yum install -y gitweb
      sudo sed -i -e 's/^#our $projectroot\s*=/our $projectroot =/' /etc/gitweb.conf
      sudo systemctl start httpd
      #echo "Provisioning done. Please access to http://$(ip -family inet addr show dev enp0s8 | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+')/git"
      echo "Provisioning done. Please access to http://$(ip -family inet addr show dev enp0s8 | grep -Eo 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | grep -Eo [0-9].*)/git"
    SHELL
  end
end
