Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
  # General
  config.vm.box = "centos67_x64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end
  config.vm.synced_folder "../binaries", "/vagrant"

  # Nodes
  config.vm.define :db001 do |sv|
    sv.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
    #sv.vm.network :private_network, ip: "192.168.33.10"
    sv.vm.hostname = "db001"
    sv.vm.provision "shell", inline: <<-SHELL
      # https://docs.oracle.com/cd/E36055_01/install.112/b66469/toc.htm
      dd if=/dev/zero of=/swap1GB bs=1G count=1 2>&1
      mkswap -f /swap1GB
      swapon /swap1GB
      swapon -s
      echo "/swap1GB                swap                    swap    defaults        0 0" >> /etc/fstab
      yum install -y glibc make binutils gcc libaio
      rpm -ivh /vagrant/oracle-xe-11.2.0-1.0.x86_64.rpm
      /etc/init.d/oracle-xe configure responseFile=/vagrant/oracle-xe.rsp
      ln -sf /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh /etc/profile.d/oracle_env.sh
      . /etc/profile.d/oracle_env.sh
      echo "EXEC DBMS_XDB.SETLISTENERLOCALACCESS(FALSE);" | sqlplus "system/$(grep ^ORACLE_PASSWORD /vagrant/oracle-xe.rsp | awk -F= '{print $2}')"
    SHELL
  end
end
